services:
  backend:
    build: 
      context: ./backend/docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    tty: true
    volumes:
      - ./backend:/backend
    depends_on:
      - mysql
    privileged: true

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    volumes:
      - ./mysql:/var/lib/mysql
    privileged: true

  # front:
  # build:
  # context: ./front/docker
  # dockerfile: Dockerfile
  # ports:
  # - "3000:3000"
  # volumes:
  # - ./front:/front
  # command: sh -c "cd /front && yarn start"
  # container_name: front
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx:/etc/nginx/conf.d
    depends_on:
      - backend

