# Generated by Django 4.1 on 2024-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickteckapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoadModel',
        ),
    ]
